import { Geist, Geist_Mono } from "next/font/google";
import Footer from "./footer/Footer";
import "./globals.css";
import Header from "./header/Header";
import "./reset.css";

import SessionProvider from "@/app/components/sessionProvider/SessProvider";
import ReduxProvider from "./redux/storeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "E-coomerce project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <ReduxProvider>
            <Header />
            {children}
            <Footer />
          </ReduxProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
